<?php
// Generate `ncaateams.list` with ESPN team IDs and display names.
// Lines starting with '#' are excluded; active lines are used by `ncaaf.php`.

require_once __DIR__ . '/espn_scores_common.php';

global $sportEndpoints;
if (!isset($sportEndpoints['ncaaf'])) {
    fwrite(STDERR, "ncaaf endpoint not configured\n");
    exit(1);
}

$ep = $sportEndpoints['ncaaf'];
$items = fetchScoreboard($ep['url'], $ep['label']);

// collect unique teams by id
$teams = [];
foreach ($items as $it) {
    $hid = $it['homeTeamId'] ?? null;
    $aid = $it['awayTeamId'] ?? null;
    $hname = $it['homeTeamName'] ?? null;
    $aname = $it['awayTeamName'] ?? null;
    if ($hid && $hname) $teams[(string)$hid] = $hname;
    if ($aid && $aname) $teams[(string)$aid] = $aname;
}

ksort($teams, SORT_NATURAL | SORT_FLAG_CASE);

// Teams to include by default (Big Ten + Central Michigan + Western Michigan)
$includeNames = [
    'Indiana Hoosiers','Maryland Terrapins','Michigan Wolverines','Ohio State Buckeyes',
    'Penn State Nittany Lions','Rutgers Scarlet Knights','Illinois Fighting Illini',
    'Iowa Hawkeyes','Minnesota Golden Gophers','Nebraska Cornhuskers','Northwestern Wildcats',
    'Purdue Boilermakers','Wisconsin Badgers','Central Michigan Chippewas','Western Michigan Broncos'
];

// normalize include set for matching
$includeLower = array_map(function($s){ return mb_strtolower($s); }, $includeNames);

$outLines = [];
$outLines[] = "# ncaateams.list — autogenerated by generate_ncaateams_list.php";
$outLines[] = "# Format: id,displayName";
$outLines[] = "# Lines starting with '#' are excluded (inactive).";
$outLines[] = "# Edit this file to enable/disable teams (leave id,displayName for enabled).";
$outLines[] = "";

foreach ($teams as $id => $name) {
    $active = 0;
    $lname = mb_strtolower($name);
    foreach ($includeLower as $inc) {
        if (mb_stripos($lname, $inc) !== false || mb_stripos($inc, $lname) !== false) {
            $active = 1;
            break;
        }
    }
    $line = $id . ',' . $name;
    if ($active) {
        $outLines[] = $line;
    } else {
        $outLines[] = '#'.$line;
    }
}

$dest = __DIR__ . '/ncaateams.list';
file_put_contents($dest, implode("\n", $outLines) . "\n");

echo "Wrote " . $dest . " (" . count($teams) . " teams, " . array_sum(array_map(function($l){ return ($l[0] !== '#') ? 1 : 0; }, $outLines)) . " active lines)\n";
exit(0);

?>
