#!/usr/bin/env pwsh
# Fetch ESPN NCAAF scoreboard and generate html/ncaateams.list

$url = 'https://site.api.espn.com/apis/site/v2/sports/football/college-football/scoreboard'
try {
    $data = Invoke-RestMethod -Uri $url -UseBasicParsing -ErrorAction Stop
} catch {
    Write-Error "Failed to fetch $url : $_"
    exit 1
}

$teams = @{}
foreach ($event in $data.events) {
    $comp = $event.competitions[0]
    if (-not $comp) { continue }
    foreach ($c in $comp.competitors) {
        $id = $c.team.id
        $name = $c.team.displayName
        if ($id -and $name) { $teams[$id] = $name }
    }
}

$sorted = $teams.GetEnumerator() | Sort-Object -Property Value

# Default includes: Big Ten + Central Michigan + Western Michigan
$includeNames = @(
    'Indiana Hoosiers','Maryland Terrapins','Michigan Wolverines','Ohio State Buckeyes',
    'Penn State Nittany Lions','Rutgers Scarlet Knights','Illinois Fighting Illini',
    'Iowa Hawkeyes','Minnesota Golden Gophers','Nebraska Cornhuskers','Northwestern Wildcats',
    'Purdue Boilermakers','Wisconsin Badgers','Central Michigan Chippewas','Western Michigan Broncos'
)
$includeLower = $includeNames | ForEach-Object { $_.ToLower() }

$out = @()
$out += '# ncaateams.list — autogenerated by tools/generate_ncaateams.ps1'
$out += '# Format: id,displayName'
$out += "# Lines starting with '#' are excluded (inactive)."
$out += "# Edit this file to enable/disable teams (leave id,displayName for enabled)."
$out += ''

foreach ($kv in $sorted) {
    $id = $kv.Key
    $name = $kv.Value
    $lname = $name.ToLower()
    $active = $false
    foreach ($inc in $includeLower) {
        if ($lname -like "*$inc*" -or $inc -like "*$lname*") { $active = $true; break }
    }
    $line = "$id,$name"
    if ($active) { $out += $line } else { $out += '#' + $line }
}

$dest = 'html/ncaateams.list'
$out -join "`n" | Set-Content -Path $dest -Encoding UTF8
Write-Output "Wrote $dest (`$($sorted.Count) teams). Active lines: $((($out | Where-Object { -not ($_.StartsWith('#')) }).Count))"

exit 0
